// Generated by jextract

package com.keygenqt.c_lib;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$0 {

    static final FunctionDescriptor getRandom$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle getRandom$MH = RuntimeHelper.downcallHandle(
        "getRandom",
        constants$0.getRandom$FUNC
    );
    static final FunctionDescriptor generateUUID$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle generateUUID$MH = RuntimeHelper.downcallHandleVariadic(
        "generateUUID",
        constants$0.generateUUID$FUNC
    );
}


